### ISSUE TITLE
Project don't run(yellow screen)

### ISSUE THREAD

**Issue by victorcarvalhosp** [ksachdeva/angular2-swing-example#1]
I clone the project, and did:

npm install
npm start

And the project don't work, only show a yellow screen and these errors on console:

GET http://localhost:3000/node_modules/core-js/client/shim.min.js 404 (Not Found)
zone.js:101 GET http://localhost:3000/node_modules/performance-now/lib/performance-now.js 404 (Not Found)
Error: Error: XHR error (404 Not Found) loading http://localhost:3000/node_modules/performance-now/lib/performance-now.js(…)

I did something wrong?

Thanks!

**Comment by ksachdeva** [comment]
@victorcarvalhosp just tried the repository with fresh install and do not see the issue.

you are getting 404 which means that most likely npm install may have failed and hence missing npm packages in node_modules.

Make sure npm install was successful
